name: Pull Request Preview

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build site
        run: npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          environment:
            name: preview
            url: ${{ steps.deployment.outputs.page_url }}

  # Add comment to PR with preview link
  comment:
    needs: build-and-preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 Preview deployment')
            )
            
            const commentBody = `## 🚀 Preview deployment ready!
            
            Your changes have been deployed to a preview environment:
            
            **🔗 Preview URL:** ${{ steps.deployment.outputs.page_url }}
            
            ### 🧪 Test the calendar integration:
            - [ ] Visit any recipe page (e.g., Turkey Dinner)
            - [ ] Scroll to "Plan Your Cooking Timeline" section
            - [ ] Test date/time picker
            - [ ] Try Google Calendar integration
            - [ ] Try Apple Calendar (ICS download)
            - [ ] Verify timeline updates correctly
            
            ### 📱 Mobile testing:
            - [ ] Test on mobile device
            - [ ] Verify responsive design
            - [ ] Test calendar buttons on mobile
            
            ---
            *This preview will be updated automatically when you push new commits to this PR.*`
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: commentBody
              })
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              })
            }
